In [1]:
import numpy as np

In [2]:
def my_func1(x):
    return x**2

In [3]:
# 미분할것임

In [4]:
def numerical_drivative(f, x):
    delta_x=1e-4
    return (f(x+delta_x)-f(x-delta_x))/(2*delta_x)

In [5]:
result=numerical_drivative(my_func1,3)
print("result=",result)

result= 6.000000000012662


In [6]:
# 수치 미분

In [7]:
import numpy as np

def my_func2(x):
    return 3*x*(np.exp(x))

In [8]:
result2=numerical_drivative(my_func2,2)
print("result ==", result2)

result == 66.50150507518049


In [9]:
def numerical_derivative(f, x): # 수치미분 debug version
    delta_x = 1e-4 
    grad = np.zeros_like(x)
    
    print("debug 1. initial input variable =", x)
    print("debug 2. initial input grad =", grad)
    print("================================== =")
    
    it = np.nditer(x, flags=['multi_index'], op_flags=['readwrite'])
    while not it.finished:
        idx=it.multi_index
        
        print("debug 3, idx=",idx,",x[idx]=",x[idx])
        
        tmp_val = x[idx]
        x[idx]=float(tmp_val)+delta_x
        fx1=f(x) #f(x+delta_x)
        
        x[idx] = tmp_val - delta_x
        fx2 = f(x) # f(x-delta_x)
        grad[idx]=(fx1-fx2)/(2*delta_x)
        
        print("debug 4. grad[idx] =",grad[idx])
        print("debug 5. grad = ", grad)
        print("=================================")
        
        x[idx] = tmp_val
        it.iternext() 
    return grad
        

In [10]:
def func2(input_obj):
    x=input_obj[0]
    y=input_obj[1]
    return (2*x + 3*x*y + np.power(y,3)) #2x + 3xy + y**3

In [11]:
numerical_derivative(func2, np.array([3.0,2.0]))

debug 1. initial input variable = [3. 2.]
debug 2. initial input grad = [0. 0.]
================================== =
debug 3, idx= (0,) ,x[idx]= 3.0
debug 4. grad[idx] = 7.999999999999119
debug 5. grad =  [8. 0.]
debug 3, idx= (1,) ,x[idx]= 2.0
debug 4. grad[idx] = 21.000000010040765
debug 5. grad =  [ 8.         21.00000001]


array([ 8.        , 21.00000001])

In [12]:
def func3(input_obj):
    w=input_obj[0]
    x=input_obj[1]
    y=input_obj[2]
    z=input_obj[3]
    return (w*x + x*y*z + 3*w + z*np.power(y,2)) #wx + xyz +3w +y**2

In [13]:
numerical_derivative(func2,np.array([3.0,2.0]))

debug 1. initial input variable = [3. 2.]
debug 2. initial input grad = [0. 0.]
================================== =
debug 3, idx= (0,) ,x[idx]= 3.0
debug 4. grad[idx] = 7.999999999999119
debug 5. grad =  [8. 0.]
debug 3, idx= (1,) ,x[idx]= 2.0
debug 4. grad[idx] = 21.000000010040765
debug 5. grad =  [ 8.         21.00000001]


array([ 8.        , 21.00000001])

In [14]:
numerical_derivative(func3,np.array([3.0,2.0,3.0,4.0]))

debug 1. initial input variable = [3. 2. 3. 4.]
debug 2. initial input grad = [0. 0. 0. 0.]
================================== =
debug 3, idx= (0,) ,x[idx]= 3.0
debug 4. grad[idx] = 5.000000000023874
debug 5. grad =  [5. 0. 0. 0.]
debug 3, idx= (1,) ,x[idx]= 2.0
debug 4. grad[idx] = 15.000000000000568
debug 5. grad =  [ 5. 15.  0.  0.]
debug 3, idx= (2,) ,x[idx]= 3.0
debug 4. grad[idx] = 31.999999999996476
debug 5. grad =  [ 5. 15. 32.  0.]
debug 3, idx= (3,) ,x[idx]= 4.0
debug 4. grad[idx] = 15.000000000000568
debug 5. grad =  [ 5. 15. 32. 15.]


array([ 5., 15., 32., 15.])

In [15]:
numerical_derivative(my_func1,np.array([3.0]))

debug 1. initial input variable = [3.]
debug 2. initial input grad = [0.]
================================== =
debug 3, idx= (0,) ,x[idx]= 3.0
debug 4. grad[idx] = 6.000000000012662
debug 5. grad =  [6.]


array([6.])